# Configuration for probot-stale - https://github.com/probot/stale
daysUntilStale: 30
daysUntilClose: 7
exemptLabels:
  - considering
  - planned
  - confirmed
exemptAssignees: true
staleLabel: stale
only: issues
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: >
  This issue has been automatically closed because it has been stale for 30
  days. You may reopen this issue by commenting on it. Thank you for your
  contributions.
limitPerRun: 30