plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id "com.modrinth.minotaur" version "2.+"
    id "com.matthewprenger.cursegradle" version "1.4.0"
    id 'net.neoforged.gradle.userdev' version "7.0.155"
    id 'com.diffplug.spotless' version '6.23.3'
    id 'org.sonarqube' version '4.4.1.3373'
}

if (project.file('../gradletools.gradle').exists()) {
    apply from: '../gradletools.gradle'
} else {
    apply from: 'https://raw.githubusercontent.com/NovaMachina-Mods/MultiWorkspace/1.21/gradletools.gradle'
}

def basicVersion = "${project.mod_version}-build." + ext.getBuildNumber()
version = "${project.minecraft_version}-${basicVersion}" + (basicVersion.endsWith("SNAPSHOT") ?  '' : (project.release_type != 'release' ? "-${project.release_type}" : ''))
group = String.format("%s.%s",project.mod_group_id, project.mod_id)

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

sourceSetConfig()
repos()
at()
runConfigurations()
jars()
ext.processResources([[ modId: "novacore", type: "required", ordering: "AFTER", side: "BOTH", versionRange: novacore_version_range]])

dependencies {
    mc()
    novacore()
}

ext.publish()

if(!System.getenv('CI')) {
    apply plugin: com.diffplug.gradle.spotless.SpotlessPlugin
    spotlessConfig()
}

localGitHook()

cfdeps([], ["novacore"], [])
modrinthConfig([], ["novacore"], [])

project.tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

ideaConfig()

sonar {
    properties {
        property "sonar.projectKey", "NovaMachina-Mods_ExNihiloSequentia"
        property "sonar.organization", "novamachina-mods"
        property "sonar.host.url", "https://sonarcloud.io"
    }
}