base_path: .
files:
  - source: /src/datagen/generated/exnihilosequentia/assets/exnihilosequentia/lang/en_us.json
    translation: /src/main/resources/assets/exnihilosequentia/lang/%locale_with_underscore%.json
  - source: /src/datagen/generated/exnihilomekanism/assets/exnihiloae/lang/en_us.json
    translation: /src/mekanism/resources/assets/exnihilomekanism/lang/%locale_with_underscore%.json
  - source: /src/datagen/generated/exnihilothermal/assets/exnihiloae/lang/en_us.json
    translation: /src/thermal/resources/assets/exnihilothermal/lang/%locale_with_underscore%.json
  - source: /src/datagen/generated/exnihilotinkers/assets/exnihiloae/lang/en_us.json
    translation: /src/tinkers/resources/assets/exnihilotinkers/lang/%locale_with_underscore%.json
