#######################
### Gradle Settings ###
#######################
org.gradle.daemon=false
org.gradle.debug=false
org.gradle.jvmargs=-Xmx5G

####################
### Mod Settings ###
####################
mod_id=exnihilosequentia
mod_version=7.0.1
mod_name=Ex Nihilo: Sequentia
mod_description=Ex Nihilo: Sequentia is a modern port of Ex Nihilo: Creatio for 1.12, which in turn was a fork of Ex Nihilo: Adscensio for 1.10, which was a continuation of Ex Nihilo for 1.7.10.
github_id=ExNihiloSequentia

########################
### Release Settings ###
########################
curseforge_id=400012
modrinth_project_id=WhVa4xyw
release_type=beta

