modLoader = "javafml" #mandatory
loaderVersion = "${loader_version}" #mandatory
license = "Creative Commons"
issueTrackerURL = "https://github.com/NovaMachina-Mods/ExNihiloSequentia-Mekanism/issues" #optional
[[mods]] #mandatory
modId = "exnihilomekanism" #mandatory
version = "${version}" #mandatory
displayName = "Ex Nihilo: Sequentia - Mekanism Addon" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ex-nihilo-sequentia-mekanism-addon/" #optional
logoFile = "logo-mekanism.png" #optional
credits = "" #optional
authors = "NovaMachina" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''
    An addon for Ex Nihilo: Sequentia that adds support for Mekanism.
    '''
[[dependencies.exnihilomekanism]]
modId = "exnihilosequentia"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.exnihilomekanism]]
modId = "mekanism"
mandatory = true
versionRange = "[1.18.2-10.2.0.459, )"
ordering = "AFTER"
side = "BOTH"
