#! /bin/bash
RUN_RESULT=$1
COLOR=$2
DISCORD_WEBHOOK=$DISCORD_WEBHOOK_URL
REPOSITORY_NAME=$(Build.Repository.Name)
BUILD_NUMBER=$(Build.BuildNumber)

if [[ -z $RUN_RESULT ]]; then
  printf "Missing run result\n"
  exit 1
fi

if [[ -z $COLOR ]]; then
  COLOR=3224808
fi

if [[ -z $DISCORD_WEBHOOK ]]; then
  printf "Missing Discord Webhook\n"
  exit 1
fi

if [[ -z $REPOSITORY_NAME ]]; then
  printf "Missing Repository Name\n"
  REPOSITORY_NAME="UNKNOWN PROJECT"
fi

if [[ -z $BUILD_NUMBER ]]; then
  printf "Missing Build Number\n"
  BUILD_NUMBER="UNKNOWN BUILD NUMBER"
fi

curl --location "$DISCORD_WEBHOOK" \
  --header 'Content-Type: application/json' \
  --data @<(cat <<EOF
{
  "embeds": [
    {
      "title": "Build $RUN_RESULT for $REPOSITORY_NAME",
      "description": "Pipeline run $BUILD_NUMBER",
      "color": $COLOR
    }
  ]
}
EOF
)