#! /bin/sh
echo "*****Running Linter******"
git stash -q --keep-index
./gradlew spotlessApply
status=$?
git stash pop -q
echo "*****Done running Linter******"
echo "*****Updating Pipeline Variables*****"
./gradlew modifyPipeline
pipelineStatus=$?
if [ $pipelineStatus = 0 ]; then
  echo "Committing change"
  git add .
  git commit --no-verify -m "Update pipeline variables"
else
  status=$pipelineStatus
fi
echo "*****Done Updating Pipeline Variables*****"

exit $status