#! /bin/sh
echo "*****Running Linter******"
git stash -q --keep-index
./gradlew spotlessApply
status=$?
echo "*****Done running Linter******"
echo "*****Updating Pipeline Variables*****"
./gradlew modifyPipeline
pipelineStatus=$?
if [ $pipelineStatus != 0 ]; then
  echo "Committing change"
  git add .
  git commit -m "Update pipeline variables"
else
  status=$pipelineStatus
fi
echo "*****Done Updating Pipeline Variables*****"
git stash pop -q

exit $status