---
name: Build 1.19
on:
  push:
    branches:
      - 1.19
  pull_request:
    branches:
      - 1.19

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Notify Discord of Run Start
        if: github.event_name != 'pull_request'
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title": "Build started for ${{github.event.repository.name}}", "color": "3224808"}]'
        with:
          args: "Pipeline run ${{github.run_number}} on branch ${{github.ref_name}} on branch ${{github.ref_name}}"
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"
      - name: Build Project
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build
      - name: Notify Discord of Succeeded Build
        if: (github.event_name != 'pull_request') && success()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title": "Build succeeded for ${{github.event.repository.name}}", "color": "3470945"}]'
        with:
          args: "Pipeline run ${{github.run_number}} on branch ${{github.ref_name}}"
      - name: Notify Discord of Failed Build
        if: (github.event_name != 'pull_request') && failure()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title": "Build failed for ${{github.event.repository.name}}", "color": "16071463"}]'
        with:
          args: "Pipeline run ${{github.run_number}} on branch ${{github.ref_name}}"

  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    needs: build
    if: false && (github.event_name != 'pull_request' && github.ref_name == '1.19')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Notify Discord of Deploy
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title": "Deploy started for ${{github.event.repository.name}}", "color": "3224808"}]'
        with:
          args: "Pipeline run ${{github.run_number}} on branch ${{github.ref_name}}"
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"
      - name: Deploy to CloudSmith
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: publish
      - name: Deploy to CurseForge
        env:
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_APIKEY }}
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: publishCurseForge
      - name: Deploy to Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: modrinth
      - name: Notify Discord of Succeeded Deploy
        if: success()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title": "Deploy succeeded for ${{github.event.repository.name}}", "color": "3470945"}]'
        with:
          args: "Pipeline run ${{github.run_number}} on branch ${{github.ref_name}}"
      - name: Notify Discord of Failed Deploy
        if: failure()
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title": "Deploy failed for ${{github.event.repository.name}}", "color": "16071463"}]'
        with:
          args: "Pipeline run ${{github.run_number}} on branch ${{github.ref_name}}"
