name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          close-issue-message: 'This issue has been automatically closed because it has been stale for 7 days. You may reopen this issue by commenting on it.'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'considering,planned,confirmed'
          exempt-all-issue-assignees: true
          days-before-stale: 30
          days-before-close: 7